// Copyright (c) 2024-2026, The VeilRoot Project
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#include <cstdint>

#include "crypto/crypto.h"
#include "ringct/rctTypes.h"
#include "governance/voting_weight.h"

namespace cryptonote {

// Per-output weighted Pedersen commitment, spec §16-§18.
//
//   Q_i = f_i * C_i                    (publicly recomputable from chain)
//   V_i = Q_i + rho_i * G              (wallet-private commitment)
//
// V_i is a Pedersen commitment to the exact voting weight
//   W_i = amount_i * f_i
// with blinding (f_i * mask_i + rho_i). Only the wallet knows rho_i.
//
// The CLSAG generated by dao_clsag_generate binds V_i to the hidden
// output via C_offset = V_i and z = -rho_i, so consensus never sees
// amount_i, mask_i, rho_i, or W_i.
struct dao_output_weight
{
    rct::key            commitment;  // V_i
    rct::key            blinding;    // rho_i
    governance_weight_t weight;      // W_i = amount_i * f_i
};

// Build V_i from the wallet's private inputs.
//
//   amount      - output amount in atomic units
//   age_factor  - f_i, from calculate_voting_weight
//   C_i         - RingCT Pedersen amount commitment for this output
//   rho_i       - fresh random scalar (wallet-private)
//
// Returns false if the output's weight exceeds governance_w_max().
bool dao_commit_output_weight(uint64_t amount,
                              uint8_t  age_factor,
                              const rct::key& C_i,
                              const rct::key& rho_i,
                              dao_output_weight& out);

} // namespace cryptonote